

--1. What is the total number of rows in each of the 3 tables in the database?

	SELECT COUNT (* )
	FROM CUSTOMER
	UNION ALL
	SELECT COUNT (* )
	FROM prod_cat_info
	UNION ALL
	SELECT COUNT (* )
	FROM Transactions

--2. What is the total number of transactions that have a return? 

	SELECT COUNT (total_amt) AS RETURN_TRANSACTION
	FROM Transactions
	WHERE total_amt < 0

/*3. As you would have noticed, the dates provided across the datasets are not in a 
correct format. As first steps, pls convert the date variables into valid date formats 
before proceeding ahead.
*/

	SELECT CONVERT(date, dob, 120) AS DOB_DATE FROM CUSTOMER
	union
	SELECT CONVERT (DATE, TRAN_DATE, 120) AS NEW_TRAN_DATE FROM Transactions

--4. What is the time range of the transaction data available for analysis? Show the 
--output in number of days, months and years simultaneously in different columns.

	SELECT DATEDIFF(DAY, MIN (TRAN_DATE), MAX(TRAN_DATE)) AS DAY_DIFF, 
		DATEDIFF(MONTH, MIN (TRAN_DATE), MAX(TRAN_DATE)) AS MONTH_DIFF,
		DATEDIFF(YEAR, MIN (TRAN_DATE), MAX(TRAN_DATE)) AS DAY_DIFF
	FROM Transactions

--5. Which product category does the sub-category “DIY” belong to? 

	SELECT DISTINCT(prod_cat)
	FROM prod_cat_info
	WHERE prod_subcat = 'DIY'

-- DATA ANALYSIS 

-- 1. Which channel is most frequently used for transactions? 

	SELECT TOP 1 STORE_TYPE
	FROM TRANSACTIONS
	GROUP BY Store_type
	ORDER BY COUNT(STORE_TYPE) DESC

--2. What is the count of Male and Female customers in the database?

	SELECT GENDER, COUNT (GENDER) AS COUNTS_GENDER
	FROM CUSTOMER
	WHERE GENDER ='F'OR GENDER = 'M'   --(2 NULL VALUES PRESENT)
	GROUP BY GENDER

--3. From which city do we have the maximum number of customers and how many?

	SELECT top 1 city_code, COUNT(city_code) AS NO_OF_CUST
	FROM CUSTOMER
	GROUP BY city_code
	ORDER BY COUNT(CITY_CODE) DESC

--4. How many sub-categories are there under the Books category?

	SELECT COUNT (prod_subcat) AS COUNT_OF_SUBCAT
	FROM prod_cat_info
	WHERE PROD_CAT = 'BOOKS'

--5. What is the maximum quantity of products ever ordered?

	SELECT max(qty) as MAX_ORDER_QTY
	FROM TRANSACTIONS

--6. What is the net total revenue generated in categories Electronics and Books?

	SELECT SUM(TOTAL_AMT) AS TOT_REV
	FROM TRANSACTIONS AS A
		INNER JOIN prod_cat_info AS B
		ON A.prod_cat_code = B.prod_cat_code AND
		A.prod_subcat_code = B.prod_sub_cat_code
	WHERE prod_cat IN ('ELECTRONICS', 'BOOKS')

-- 7. How many customers have >10 transactions with us, excluding returns?

	SELECT COUNT (COUNT_CUST) AS NO_OF_CUST
	FROM (
		SELECT COUNT (CUST_ID) AS COUNT_CUST
		FROM TRANSACTIONS
		WHERE TOTAL_AMT > 0
		GROUP BY CUST_ID
		HAVING COUNT (TRANSACTION_ID) > 10) AS X

--8. What is the combined revenue earned from the “Electronics” & “Clothing” 
--categories, from “Flagship stores”?

	SELECT SUM (TOTAL_AMT) AS COMBINED_REV
	FROM Transactions AS A
		INNER JOIN prod_cat_info AS B
		ON	A.prod_cat_code = B.prod_cat_code AND
		A.prod_subcat_code = B.prod_sub_cat_code
	WHERE prod_cat IN ('ELECTRONICS', 'CLOTHING') AND Store_type = 'FLAGSHIP STORE'

--9. What is the total revenue generated from “Male” customers in “Electronics” 
--category? Output should display total revenue by prod sub-cat. 

	SELECT PROD_SUBCAT, SUM (TOTAL_AMT) AS TOTAL_REV
	FROM prod_cat_info AS A INNER JOIN
		Transactions AS B
		ON A.prod_cat_code = B.prod_cat_code AND
		A.prod_sub_cat_code = B.prod_subcat_code
		INNER JOIN Customer AS C
		ON B.cust_id = C.customer_Id
	WHERE Gender = 'M' AND prod_cat = 'ELECTRONICS'
	GROUP BY prod_subcat

--10.What is percentage of sales and returns by product sub category; display only top 
--5 sub categories in terms of sales?


	SELECT TOP 5 prod_subcat, 
		(SUM (TOTAL_AMT)/(SELECT SUM(TOTAL_AMT) FROM Transactions)) * 100 AS SALES_PERCNT,
		(count(CASE WHEN Qty < 0 THEN QTY ELSE NULL END)/
		sum(Qty)) * 100 AS RETURN_PERCNT
	FROM prod_cat_info AS A
		INNER JOIN Transactions AS B
		ON A.prod_cat_code = B.prod_cat_code AND
		A.prod_sub_cat_code = B.prod_subcat_code
	GROUP BY prod_subcat
	ORDER BY SUM (TOTAL_AMT) DESC 

--11. For all customers aged between 25 to 35 years find what is the net total revenue 
--generated by these consumers in last 30 days of transactions from max transaction 
--date available in the data?

	SELECT SUM (TOTAL_AMT) AS TOT_REV
	FROM Transactions AS A
		INNER JOIN CUSTOMER AS B
	ON A.CUST_ID = B.CUSTOMER_ID
	WHERE DATEDIFF ( DAY, CONVERT (DATE, TRAN_DATE, 120),
			(SELECT MAX (CONVERT(DATE, TRAN_DATE, 120)) FROM Transactions)) <=30
			AND
			DATEDIFF (YEAR, CONVERT(DATE, DOB, 120), GETDATE ()) BETWEEN 25 AND 35


--12.Which product category has seen the max value of returns in the last 3 months of 
--transactions?

	SELECT TOP 1 PROD_CAT
	FROM (
			SELECT PROD_CAT, ABS(SUM(TOTAL_AMT)) AS TOT_SUM
			FROM PROD_CAT_INFO AS A
			INNER JOIN TRANSACTIONS AS B
			ON A.PROD_CAT_CODE = B.PROD_CAT_CODE AND
			A.PROD_SUB_CAT_CODE = B.PROD_SUBCAT_CODE
			WHERE TOTAL_AMT < 0 AND 
			DATEDIFF ( MONTH, CONVERT (DATE, TRAN_DATE, 120),
			(SELECT MAX (CONVERT(DATE, TRAN_DATE, 120)) FROM Transactions)) <=3
			GROUP BY PROD_CAT ) AS X
	ORDER BY TOT_SUM DESC
			

--13.Which store-type sells the maximum products; by value of sales amount and by 
--quantity sold? 

	SELECT TOP 1 STORE_TYPE
	FROM TRANSACTIONS
	GROUP BY Store_type
	ORDER BY SUM (TOTAL_AMT) DESC, SUM (QTY) DESC

--14.What are the categories for which average revenue is above the overall average. 

	SELECT prod_cat
	FROM prod_cat_info AS A
	INNER JOIN Transactions AS B
	ON A.prod_cat_code = B.prod_cat_code AND
	A.prod_sub_cat_code = B.prod_subcat_code
	GROUP BY prod_cat
	HAVING AVG (TOTAL_AMT) > (SELECT AVG (TOTAL_AMT) FROM Transactions)

--15. Find the average and total revenue by each subcategory for the categories which 
--are among top 5 categories in terms of quantity sold.

	SELECT PROD_SUBCAT, AVG (TOTAL_AMT) AS AVG_AMT, SUM (TOTAL_AMT) AS SUM_AMT
	FROM prod_cat_info AS X
	INNER JOIN Transactions AS Y
	ON X.prod_cat_code = Y.prod_cat_code AND
	X.prod_sub_cat_code = Y.prod_subcat_code
	WHERE PROD_CAT IN
			(SELECT TOP 5 prod_cat 
			FROM prod_cat_info AS A
			INNER JOIN Transactions AS B
			ON A.prod_cat_code = B.prod_cat_code AND
			A.prod_sub_cat_code = B.prod_subcat_code
			GROUP BY prod_cat
			ORDER BY SUM (QTY) DESC)
	GROUP BY prod_subcat


